
import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { DropletIcon, TrendingUpIcon, BrainIcon, ShieldIcon } from "lucide-react";
import Navigation from "@/components/Navigation";

const Index = () => {
  const navigate = useNavigate();
  const [isLoaded, setIsLoaded] = useState(false);

  useEffect(() => {
    // Simulate loading to allow animations to run
    const timer = setTimeout(() => {
      setIsLoaded(true);
    }, 100);
    return () => clearTimeout(timer);
  }, []);

  const features = [
    {
      title: "Precise Predictions",
      description: "Leveraging advanced machine learning for accurate flood risk assessments based on multiple environmental factors.",
      icon: TrendingUpIcon,
      delay: "100"
    },
    {
      title: "AI-Powered Insights",
      description: "Generated by Google's Gemini 1.5 Pro, providing contextual understanding of flood risk patterns and preventive measures.",
      icon: BrainIcon,
      delay: "200"
    },
    {
      title: "Preventive Planning",
      description: "Equip communities and organizations with data-driven intelligence to prepare for and mitigate potential flooding events.",
      icon: ShieldIcon,
      delay: "300"
    }
  ];

  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      
      {/* Hero Section */}
      <section className="relative pt-32 pb-20 md:pt-40 md:pb-28 bg-gradient-to-b from-accent via-background to-background overflow-hidden">
        <div className="absolute inset-0 bg-grid-pattern opacity-5"></div>
        
        {/* Abstract shapes */}
        <div className="absolute top-40 right-0 w-48 h-48 bg-primary/10 rounded-full blur-3xl"></div>
        <div className="absolute -bottom-20 left-20 w-72 h-72 bg-blue-200/30 rounded-full blur-3xl"></div>
        
        <div className="container mx-auto px-4 sm:px-6 relative">
          <div className="max-w-4xl mx-auto text-center">
            <div className={`inline-flex items-center px-4 py-2 rounded-full bg-primary/10 mb-5 text-sm text-primary font-medium transition-all transform ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`}>
              <DropletIcon className="w-4 h-4 mr-2" />
              Advanced Flood Prediction System
            </div>
            
            <h1 className={`text-4xl md:text-5xl lg:text-6xl font-bold tracking-tight text-gray-900 mb-6 transition-all transform ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`} style={{ transitionDelay: "75ms" }}>
              Intelligent Flood Risk <span className="text-primary">Prediction</span> with AI Insights
            </h1>
            
            <p className={`text-xl text-gray-600 max-w-3xl mx-auto mb-8 transition-all transform ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`} style={{ transitionDelay: "150ms" }}>
              Harness the power of machine learning and AI to forecast flood risks with precision. Make informed decisions with data-driven insights generated by Google Gemini.
            </p>
            
            <div className={`flex flex-col sm:flex-row justify-center gap-4 transition-all transform ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`} style={{ transitionDelay: "225ms" }}>
              <Button 
                size="lg" 
                className="bg-primary hover:bg-primary/90 text-white rounded-full px-8 shadow-lg hover:shadow-xl transform hover:-translate-y-1 transition-all"
                onClick={() => navigate("/dashboard")}
              >
                Start Predicting
              </Button>
              <Button 
                variant="outline" 
                size="lg" 
                className="rounded-full px-8 border-gray-300 hover:bg-gray-50 transform hover:-translate-y-1 transition-all"
              >
                Learn More
              </Button>
            </div>
          </div>
        </div>
      </section>
      
      {/* Features Section */}
      <section className="py-20 bg-white">
        <div className="container mx-auto px-4 sm:px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl font-bold text-gray-900 mb-4">Intelligent Flood Forecasting</h2>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Our system combines environmental data analytics with cutting-edge AI to deliver actionable flood risk insights.
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {features.map((feature, i) => (
              <div 
                key={i} 
                className={`bg-white p-8 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md hover:border-primary/20 transition-all duration-300 transform ${isLoaded ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-4'}`}
                style={{ transitionDelay: `${feature.delay}ms` }}
              >
                <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center mb-5">
                  <feature.icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-3">{feature.title}</h3>
                <p className="text-gray-600">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>
      
      {/* CTA Section */}
      <section className="py-20 bg-accent">
        <div className="container mx-auto px-4 sm:px-6">
          <div className="max-w-4xl mx-auto text-center">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">Ready to predict and prevent flood risks?</h2>
            <p className="text-xl text-gray-600 mb-8">
              Access our dashboard to input environmental data and receive AI-enhanced flood risk assessments.
            </p>
            <Button 
              size="lg" 
              className="bg-primary hover:bg-primary/90 text-white rounded-full px-8 shadow-lg"
              onClick={() => navigate("/dashboard")}
            >
              Go to Prediction Dashboard
            </Button>
          </div>
        </div>
      </section>
      
      {/* Footer */}
      <footer className="py-8 bg-gray-50 border-t border-gray-200">
        <div className="container mx-auto px-4 sm:px-6">
          <div className="flex flex-col items-center justify-center">
            <DropletIcon className="h-8 w-8 text-primary mb-2" />
            <p className="text-gray-600 text-sm">
              FloodWise<span className="font-light">AI</span> — Intelligent Flood Risk Prediction System
            </p>
            <div className="mt-3 text-sm text-gray-500">
              © {new Date().getFullYear()} FloodWiseAI. All rights reserved.
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Index;
